import type { Metadata } from "next";
import {
  Cardo,
  Caudex,
  Geist,
  Geist_Mono,
  MedievalSharp,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const medieval = MedievalSharp({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-medieval",
  display: "swap",
});

const cardo = Cardo({
  weight: "700",
  variable: "--font-cardo",
});

const caudex = Caudex({
  weight: "400",
  variable: "--font-caudex",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${medieval.variable} ${cardo.variable} ${caudex.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
